### ISSUE TITLE
can't use Mac Edge Dev 

### ISSUE THREAD

**Issue by richardsprague** [timf34/Substack2Markdown#1]
I'm unable to get the script to work using 

```python
# Specify the path to Microsoft Edge Dev
edge_binary_path = "/Applications/Microsoft Edge Dev.app/Contents/MacOS/Microsoft Edge Dev" 

# Set the Edge options
options = EdgeOptions()
options.binary_location = edge_binary_path
```

Is there something else I need to modify?

**Comment by timf34** [comment]
Hi Richard,
Sorry I don't have a Mac but I should be able to try out passing a path directly on my laptop this weekend, let me get back to you!
Thanks
Tim

**Comment by fteem** [comment]
+1 to this - would love to be able to pass a path to Edge as argument

**Comment by timf34** [comment]
3ad317511e907e684db1237ef5e68620257df8d5

**Comment by timf34** [comment]
49b45b452de4e18104d021779f08c06bee489eef

**Comment by timf34** [comment]
Just pushed a fix now. You can pass direct paths to your Edge and EdgeDriver executables via the CLI or just setting the defaults in the argeparse to your paths. 

It works locally for me on Windows, please let me know if it works for you guys. It needs to be the full path to the `.exe` files.

And please drop a star if you find this useful!
