### ISSUE TITLE
[BUG] Date field in metadata is always empty

### ISSUE THREAD

**Issue by Gleeful2862** [timf34/Substack2Markdown#15]
Date is not getting populated in the metadata either - all I see is

"date": "",

Likes count is getting populated properly - but not the Date.

I see the same behavior with

https://www.thefitzwilliam.com/archive?sort=new
https://www.lennysnewsletter.com/archive?sort=new
- Even with premium membership

**Comment by Firevvork** [comment]
Yes, that was a bug. I've fixed it and submitted a PR.
