### ISSUE TITLE
[Feature request] Metadata for posts?

### ISSUE THREAD

**Issue by gllg4009** [timf34/Substack2Markdown#2]
Thank you for developing this! 

I was wondering if you might consider adding the option to download the metadata (i.e., author name, date created, etc.) for the posts. 

Thanks again!

**Comment by timf34** [comment]
Hi there,

Yep it was a feature I was looking at! Not sure what the best way is to integrate this into the markdown files is... would you have any suggestions? I'll have a proper look this weekend. 

Thanks
Tim

**Comment by gllg4009** [comment]
I see your concern about the metadata messing up the format of the md file. Maybe having the metadata in a separate csv file would work!

**Comment by timf34** [comment]
@gllg4009 check out my new release, [v2.0.0](https://github.com/timf34/Substack2Markdown/releases/tag/v2.0.0)!

It now downloads metadata such as the like count and the date published. I also built a html interface which lets you browse through and sort the downloaded files. Install the markdown viewer extension and you can view everything from your browser. 

Give this project a star if you found it useful!

**Comment by gllg4009** [comment]
Fantastic @timf34 !!! I starred the project:)
