### ISSUE TITLE
premium posts are only downloaded as previews

### ISSUE THREAD

**Issue by singulararmchair** [timf34/Substack2Markdown#20]
As the title says, downloading posts from a newsletter I'm a paid subscriber to doesn't seem to work. I successfully go through the whole login thing with Microsoft Edge, but during download every post that appears has the "This post is for paid subscribers" banner at the bottom, and indeed, the resulting .md files are the preview versions only.

**Comment by timf34** [comment]
You are inputting your login details yes with the same account that's subscribed into config.py?

**Comment by singulararmchair** [comment]
The script is correctly inputting my login details.
When I run it, a Firefox window is opened, the credentials are pasted automatically, but then I receive an email asking me to complete the login before the downloading process can start. Is that supposed to be the correct sequence?

**Comment by timf34** [comment]
Can you send a screenshot? 

It should open the browser, login (which you should see in front of you), then start opening and downloading the articles right in front of you.

**Comment by singulararmchair** [comment]
Figured it out. Had log in to Substack with my password on Edge **before** running the script at all (so out of the MS loop I didn't realize Edge was a browser!). Now the premium posts are downloading correctly.

**Comment by timf34** [comment]
Glad to hear - give the project a star if you found it useful!
