### ISSUE TITLE
Issue with Edge when logging in

### ISSUE THREAD

**Issue by HansMellman** [timf34/Substack2Markdown#23]
I'm having an issue running the script - I have Edge downloaded, though Chrome is my primary browser. I've saved my credentials in the config as I'm looking to pull down a subscription substack - I've filled out all the details hardcoded at the top of the file. When the program attempts to login through Edge it enters my email but then gets hit with a page stating that I need to check my email in order to proceed. Upon checking my email I get the below:

"Did you just sign into your Substack account?"

"We blocked an unrecognised login to your Substack account"
 "If this was you click sign in now below"
And then some geo location data pertaining to me. 

Okay, maybe it's not used to me logging in from Edge - so I do that, I navigate to substack and click around make sure that I log in with username and password and autosave it to Edge. 

However, when I run the script again, it does the same thing - so it keeps failing to pull the paid content and just pulling the free content which is a tiny portion of the Substack I am looking to archive. 

How can I navigate this? I couldn't find anything in the ReadME that mentioned it, other than the need to have Edge installed (which I did prior anyway). 

Any help would be great!

**Comment by HansMellman** [comment]
Okay, after adding a User-Agent to the Init of the premiumscraper that seems to have bypassed the above issue. 

However, I did get this print out to the console throughout the process. 

`[16744:1180:1109/173556.727:ERROR:edge_auth_errors.cc(523)] EDGE_IDENTITY: Get Default OS Account failed: Error: Primary Error: kImplicitSignInFailure, Secondary Error: kAccountProviderFetchError, 
Platform error: 0, Error string:

 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                      | 80/93 [03:40<00:18,  1.44s/it][16744:1180:1109/174015.697:ERROR:fallback_task_provider.cc(127)] Every renderer should have at least one task provided by a primary task provider. If a "Renderer" fallback task is shown, it is a bug. If you have repro steps, please file a new bug and tag it as a dependency of crbug.com/739782.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 93/93 [04:02<00:00,  2.60s/it]
[16900:14960:1109/174036.160:ERROR:command_buffer_proxy_impl.cc(324)] GPU state invalid after WaitForGetOffsetInRange.`

Just going to cross reference the local files now to see if it pulled everything - though it did finish, so I am very pleased!

**Comment by HansMellman** [comment]
Adding the user-agent info was sufficient to pull all the paid content, so I didn't worry about those error messages in the end! This is a great tool - thanks for making it!

If you wanted to troubleshoot these or need any further info from me, just let me know

**Comment by timf34** [comment]
Ah that's great to hear Hans, glad to hear its useful, will close this issue for now:)
Tim

**Comment by oarbez** [comment]
@HansMellman I am having the same issue, can you please share how you edited the code to add the User Agent ?

**Comment by HansMellman** [comment]
> @HansMellman I am having the same issue, can you please share how you edited the code to add the User Agent ?

Hello! Apologies for the delay - as mentioned in my original comment, I added the information to the __init__ of the PremiumSubstackScraper class, as per below.

![image](https://github.com/user-attachments/assets/e9db5097-f3f3-4a30-a8c4-5fd1500b8efa)

**Comment by abhishekm1992** [comment]
@HansMellman Thanks for sharing the edited code! Even after adding the code though, I get the same error. I am wondering if VPN configuration has anything to do with this

```
Exception: Warning: Login unsuccessful. Please check your email and password, or your account status.
Use the non-premium scraper for the non-paid posts. 
If running headless, run non-headlessly to see if blocked by Captcha.``
```
