### ISSUE TITLE
[Feature request] Comments?

### ISSUE THREAD

**Issue by lin-things** [timf34/Substack2Markdown#3]
I was wondering if you might consider adding the option of downloading the comments for a post. Thank you!

**Comment by Firevvork** [comment]
I'm curious about why you need this feature?
Are you a substack writer? Or want to getting information from comments of the post?
Let's we know the reason so we could consider develop this feature.

**Comment by timf34** [comment]
Hey @lin-things, I personally don't like including the idea of including comments from an aesthetic standpoint. Happy to look at a PR to include comments optionally though as a flag perhaps for those who might want it

**Comment by tobicodes** [comment]
One use-case I have for comments is for creating a "What readers are saying" or "Wall of love" from my personal archive. My substack has ~100 essays.  Pretty helpful to have a dump of all comments aggregated in one place that I can search and choose the best ones from!

Is this something you'd re-consider working on @timf34 @Firevvork ? Thanks

**Comment by tobicodes** [comment]
Also, thank you for making this!

**Comment by milahu** [comment]
fixed in https://github.com/milahu/substack2markdown/commit/153746f5b76d664526db9580259d3be6aa4bcd59
