### ISSUE TITLE
Substack Requiring Captcha at Login

### ISSUE THREAD

**Issue by sam-hatley** [timf34/Substack2Markdown#4]
## Description
When using the premium scraper in headless mode, I received the below error:
```
Exception: Warning: Login unsuccessful. Please check your email and password, or your account status.
Use the non-premium scraper for the non-paid posts.
```
After investigating this error, I noticed that Substack was throwing a captcha within an `error-container`.
## Screenshot
![ss_captcha](https://github.com/timf34/Substack2Markdown/assets/111293111/967da2f6-fba3-4832-9a34-c3d2f207edf0)
## Fix
Issue can be resolved by adding a valid user agent to `EdgeOptions()` in `PremiumSubstackScraper`. The below works on my end:
```py
options.add_argument(
    "--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.246"
)
```

**Comment by timf34** [comment]
Thanks Sam! 

Added passing a user agent as an option which should make this easer. I can't simulate the captcha error so can't raise an exception especially for it, but have added a note to the general login failure exception. Thanks for sorting out
