### ISSUE TITLE
[Feature Request] Add date of posts to their file names

### ISSUE THREAD

**Issue by Gleeful2862** [timf34/Substack2Markdown#6]
so that they can be seen in the order they need to be seen as (even when seeing in the folder)

**Comment by timf34** [comment]
Thanks for the suggestion but sorry, stylistically I prefer having alphabetical order personally - but with the option to view by date in the html . It'd be easy enough to adjust the string on your end though anyways for yourself

**Comment by Gleeful2862** [comment]
Substack is a "Newsletter" website and Newsletters generally have their relevance "temporally" (in the context of the time they were written in).

Every subject evolves over time and some article/blog by the same author, say written on Agile in 2015 is most likely very little relevant compared to 2024. So, readers of Substack prefer to pick more recent articles and hence being able to see dates prominently helps with that expectation. That is the very reason why Substack and Medium lists articles as per timeline.

While a product owner might be stylistic personal preference of alphabetical order, when designing a product, it is generally helpful to build features based on the default expectations from a product its default context.

**Comment by timf34** [comment]
Thanks for the feedback, the dates are in the metadata, but don't want to include in the title

**Comment by timf34** [comment]
Feel free to fork!

**Comment by Gleeful2862** [comment]
Date is not getting populated in the metadata either - all I see is
```
"date": "",
```

I see the same behavior with
1. https://www.thefitzwilliam.com/archive?sort=new
2. https://www.lennysnewsletter.com/archive?sort=new
       - Even with premium membership

**Comment by timf34** [comment]
Ak ok thanks, I'll give that a look

**Comment by Gleeful2862** [comment]
I opened a separate bug for the Date issue as it is different from the feature this issue is about.
