### ISSUE TITLE
[Feature Request] Rather than opening the file://<file-name>.md why not embed it into a html to cleanly view it?

### ISSUE THREAD

**Issue by Gleeful2862** [timf34/Substack2Markdown#7]
Using md to html web component like 

https://zerodevx.github.io/zero-md/

or 

https://github.com/leaverou/md-block

**Comment by timf34** [comment]
Hi there,

This is a fantastic suggestion - thank you! 

I'm busy with exams until early May but you can expect this soon thereafter. Feel free to make a PR in the meantime!

**Comment by timf34** [comment]
@OisinThomas 's PR #10 fixes this, and #11 maintains backwards compat

**Comment by Gleeful2862** [comment]
I lost track of this repo and effort as there was a long gap between the original filing and follow up. I will check it out. Thank you for taking time to add the feature.
